# -*- coding: utf-8 -*-
"""actividad - operaciones math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItAckNIibtDF5l-fK7LCOst7xKW8Q0Pr
"""

import math

# Punto A #
int= a= 2+(3*(6/2));
print (a);


# Punto B #
int = b= ((4+6)/(2+3));
print(b);

# Punto C #
int=c= pow(4/2, 5);
print(c);

# Punto D #
int=d= pow(4/2, 5+1);
print(d);

# Punto E #
int=e= pow(-3, 2);
print(e);

# Punto F #
int=c= -pow(3, 2);
print(c);