# -*- coding: utf-8 -*-
"""clase 3 programación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFfLBH-DfplmULbOrYZ5PCr660Rwzz-L
"""

#ejercicio
#hallar la suoperficie de un cuadrado
import math;
"""
#se puede hacer de esta forma
lado = input("Ingrese la medida del lado del cuadrado: ");
lado= int(lado);

lado = int (input("Ingrese la medida del lado del cuadrado: ")) #forma simplificada
superficie=lado*lado
print("la superficie del cuadrado es de: ")
print(superficie)


#Ejercicio: asigna 2 valores booleanos y realiza operaciones lógicas (AND, OR, NOT).

bool1=True
bool2=False

resultado_and =
print



#estructura simple#
cal1 = float (input("Ingrese la nota 1 del estudiante "));
cal2 = float(input("Ingrese la nota 2 del estudiante "));
cal3 =float (input("Ingrese la nota 3 del estudiante "));

prom =  (cal1+cal2+cal3)/3
if prom>=70:
    print("aprobó")

else:{
    print("no aprobó")
}

 #estrutura anidada (arreglar)#

num1 = float (input("Ingrese la nota 1 del estudiante "));
num2= float(input("Ingrese la nota 2 del estudiante "));
if (num1==num2):
    int=result=num1*num2;
else:
     if (num1>num2):
         int=result=num1-num2;
    else:
        int=result=num1+num2;

print(result);
"""
#estrucutura condicional
#ejercicio 1

#ejercicio
#hallar la suoperficie de un cuadrado
import math;
"""
#se puede hacer de esta forma
lado = input("Ingrese la medida del lado del cuadrado: ");
lado= int(lado);

lado = int (input("Ingrese la medida del lado del cuadrado: ")) #forma simplificada
superficie=lado*lado
print("la superficie del cuadrado es de: ")
print(superficie)


#Ejercicio: asigna 2 valores booleanos y realiza operaciones lógicas (AND, OR, NOT).

bool1=True
bool2=False

resultado_and =
print



#estructura simple#
cal1 = float (input("Ingrese la nota 1 del estudiante "));
cal2 = float(input("Ingrese la nota 2 del estudiante "));
cal3 =float (input("Ingrese la nota 3 del estudiante "));

prom =  (cal1+cal2+cal3)/3
if prom>=70:
    print("aprobó")

else:{
    print("no aprobó")
}

 #estrutura anidada (arreglar)#

num1 = float (input("Ingrese la nota 1 del estudiante "));
num2= float(input("Ingrese la nota 2 del estudiante "));
if (num1==num2):
    int=result=num1*num2;
else:
     if (num1>num2):
         int=result=num1-num2;
    else:
        int=result=num1+num2;

print(result);
"""
#estrucutura condicional
#ejercicio 1

#ejercicio
#hallar la suoperficie de un cuadrado
import math;
"""
#se puede hacer de esta forma
lado = input("Ingrese la medida del lado del cuadrado: ");
lado= int(lado);

lado = int (input("Ingrese la medida del lado del cuadrado: ")) #forma simplificada
superficie=lado*lado
print("la superficie del cuadrado es de: ")
print(superficie)


#Ejercicio: asigna 2 valores booleanos y realiza operaciones lógicas (AND, OR, NOT).

bool1=True
bool2=False

resultado_and =
print



#estructura simple#
cal1 = float (input("Ingrese la nota 1 del estudiante "));
cal2 = float(input("Ingrese la nota 2 del estudiante "));
cal3 =float (input("Ingrese la nota 3 del estudiante "));

prom =  (cal1+cal2+cal3)/3
if prom>=70:
    print("aprobó")

else:{
    print("no aprobó")
}

 #estrutura anidada (arreglar)#

num1 = float (input("Ingrese la nota 1 del estudiante "));
num2= float(input("Ingrese la nota 2 del estudiante "));
if (num1==num2):
    int=result=num1*num2;
else:
     if (num1>num2):
         int=result=num1-num2;
    else:
        int=result=num1+num2;

print(result);
"""
#estrucutura condicional
#ejercicio 1
hrex = float(input("Ingrese el numero de horas extras del trbajador "));
sueldo = float(input("Ingrese el sueldo trbajador "));

if hrex>40:
  if  hrex==8:
    tal= hrex*2;
    if hrex>8: