# -*- coding: utf-8 -*-
"""clase 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZDjh1L6owkPcAha_ZOH1Q3FZUYrXkgA
"""

'''
a= "hello world"
print(a)
x=1
y=2.8
z=1j
b=35e3
c=12E4
d=-87.7e100
e=3+5
f=5j
g=-5j
print(type(x))
print(type(y))
print(type(z))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))


x=1
y=2.8
z= 1j
a=float(x)
b=int(y)
c= complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type (b))
print(type(c))

print(10 > 9)

print(bool("hola"))


#ejercico: evaluar los tipos de datos
x=1
y=3.14
z=1+2j
print(type(x))
print(type(y))
print(type(z))



#ejerccicio: sumar numeros compllejos
a=4j
b=5j
print(a+b)

##operadores  ej
x=7
y=5
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x**y)
print(x//y)

#comparación
x=5
y=4
print(x==y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)

#logicos
x=5
print(x>3andx<10)
print(x>3andx<4)
print(not(x>3andx<10))



#identidad
x=["manzana", "limon"]
y=["manzana", "limon"]
z=x
print(x is z)
print(x is y)
print(x == y)

#pertenencia

x=["manzana", "limon"]
print("manzana" in x)
print("pera" not in x)

#encontrar max y min
x=min(5,10,6)
y=max(5,10,6)
print(x)
print(y)

#potencia
x=pow(4,3)
print(x)

#raiz
import math
x=math.sqrt(64)
print(x)

a=math.ceil(1.4)
b=math.floor(1.4)
print(a)
print(b)
c=math.pi
print(c)
'''

#ejercicio
a=2+(3*(6/2))
b=((4+6)/(2+3))
c=(4/2)

print(b)