# -*- coding: utf-8 -*-
"""Parcial1-2025-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14b6lsYA_PLVwoBtePkS_aZyXc8kt-Kst

Integrantes: Adrian David Yepes Lopez & Johan Sebastian Beleño Toloza.
Fecha: 17/oct/2025
"""

## ejercicio 3 y 4

"""
3. Suma de los números impares:
Pide al usuario un número entero positivo n y calcula
la suma de todos los números impares desde 1 hasta
n.
"""
#datos de entrada:
n= int( input("Ingrese un número para obtener los impares hasta ese: ")) #se piden datos

#####################

#proceso y datos de salida:

if n %2!=0: # se verifican si el dato ingresado es par en caso de serlo envia un mensaje (no valido)
  print("es impar")

  for i in range(1,n+1): # se usa un ciclo for para recoer mediante la sigiente operación, para identificar los impares usando i como contador
    if i %2!=0:
      print(i)

else:
   print("es par","\n","numero invalido, solo se aceptan impares")

from re import split


"""
Lista sin duplicados:
Dada una lista ingresada por el usuario (separada por
comas), elimina los elementos duplicados y muestra
la lista
resultante sin repeticiones.
"""
#datos de entrada

# Solicita al usuario una lista separada por comas
entrada = input("Ingrese los elementos separados por comas (sin espacios): ")

#proceso

# Convierte la entrada en una lista y elimina duplicados
lis = entrada.split(",")
lis_ndup = list(set(lis))

#envio de datos al usuario:
print("Lista sin duplicados:", lis_ndup)