# -*- coding: utf-8 -*-
"""clase1-corte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBqEI_XXtS8QRNav-51VFXRHdOxXOaHP
"""

import numpy as np #se importa la librería
mi_array = np.arange(1000000)
mi_lista=list(range(1000000))
print(mi_lista)
# ----------------------------------------

import numpy as np #se importa la librería
data1=[6, 7.5, 8, 0, 1]
arr1=np.array(data1)
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)

"""creando ndarry"""

#suma las listas
import numpy as np
data2=[[1, 2, 3, 4], [5, 6, 7, 8]] #list of list
arr2 =np.array(data2)
print(arr2.ndim)#2
print(arr2.shape)#(2,4)

#--------------------------------
print("-------------------------------")
#opraciones aritmeticas ente matrices
arr=np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

print("-------------------------------")

print (arr * arr)
print("-------------------------------")
print (arr - arr)
print("-------------------------------")

import numpy as np
arr=np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print("-------------------------------")
print (arr **2)


#indexación y segmentación

#indexación y segmentación
import numpy as np
arr=np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8]=12
print(arr)

print("-------------------------------")

arr= np.arange(10)
print(arr)
arr_slice=arr[5:8]
print(arr_slice)
arr_slice[1]=12345
print(arr)
arr_slice[:]=64
print(arr)

print("-------------------------------")

#indexación

arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])

"""Ejercicio1"""

import numpy as np
#conciderar la siguente matriz bidimencional
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#escribir un code para cut esta matriz para mostrar la ultima columna [[3][6][9]]
#escribe un code que corte this array for show the 2 last elements of center array : [5,6]
print(arr2d[:,2:])
print(arr2d[1,1:])

"""Pandas"""

from pandas import Series, DataFrame
import pandas as pd

obj=Series([4, 7, -5, 3])
print(obj)
print(obj.index)
print(obj.values)

"""EJERCICO

---


"""

import pandas as pd
import random

# lista aleatoria de 10 números

lista = []
for i in range(10):          # igual que arr_slice
    lista.append(random.randint(1, 100))

print("Lista original:")
print(lista)

#Serie usando el mismo estilo de clase

serie = pd.Series(lista)
serie.index = range(1, 11)   # cambiar el índice (como en clase .index)
serie.name = "Números aleatorios"
serie.index.name = "idx"

print("\nSerie:")
print(serie)
print("\nÍndice de la serie:")
print(serie.index)
print("\nValores de la serie:")
print(serie.values)


# serie de cuadrados (igual que arr2d**2)

cuadrados = serie ** 2

print("\nSerie de cuadrados:")
print(cuadrados)


#los últimos 4 elementos (como arr[5:8])

print("\nÚltimos 4 elementos:")
print(cuadrados[-4:])   # slicing como en NumPy

# Filtrar valores

filtro = cuadrados[cuadrados > 500]

print("\nValores mayores a 500 (con índice):")
print(filtro)

print("\nValores mayores a 500 como lista:")
print(filtro.values.tolist())