# -*- coding: utf-8 -*-
"""elercicio-clase 1 - corte3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC7aQbDJbdgs5Exp4Vt3_8UagzYyMUJv
"""

# Alumno: Johan Sebastian Beleño Toloza
import pandas as pd
import random

# lista aleatoria de 10 números

lista = []
for i in range(10):          # igual que arr_slice
    lista.append(random.randint(1, 100))

print("Lista original:")
print(lista)

#Serie usando el mismo estilo de clase

serie = pd.Series(lista)
serie.index = range(1, 11)   # cambiar el índice (como en clase .index)
serie.name = "Números aleatorios"
serie.index.name = "idx"

print("\nSerie:")
print(serie)
print("\nÍndice de la serie:")
print(serie.index)
print("\nValores de la serie:")
print(serie.values)


# serie de cuadrados (igual que arr2d**2)

cuadrados = serie ** 2

print("\nSerie de cuadrados:")
print(cuadrados)


#los últimos 4 elementos (como arr[5:8])

print("\nÚltimos 4 elementos:")
print(cuadrados[-4:])   # slicing como en NumPy

# Filtrar valores

filtro = cuadrados[cuadrados > 500]

print("\nValores mayores a 500 (con índice):")
print(filtro)

print("\nValores mayores a 500 como lista:")
print(filtro.values.tolist())