# -*- coding: utf-8 -*-
"""clase 2-corte2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2iN4kGO6YV7RpDFc8e0Ury2lozTvxV4

Practica en clase
"""



lista=["a","b","c","d","e"]

#accediendo al elemento 1 (indice 0)
primer_elemento=lista[0]
print("primer elemento", primer_elemento)
#accediendo al elemento 1 (indice 1)
seg_elemento=lista[1]
print("segundo elemento", seg_elemento)
#accediendo al elemento 1 (indice 2)
ter_elemento=lista[2]
print("tercer elemento", ter_elemento)
#accediendo al elemento 1 (indice 3)
cuar_elemento=lista[3]
print("cuarto elemento", cuar_elemento)
#accediendo al elemento 1 (indice 4)
quin_elemento=lista[4]
print("quinto elemento", quin_elemento)

print("-----------------------------")
#conocer el numero de elementos
num_elementos=len(lista)
print("numero de elementos", num_elementos)


print("----------------------------")
#calcular el indice
indice= 2+1

#accedemeos al elemento
elemento=lista[indice]
print("elemento en el indice", indice, "es", elemento)


print("----------------------------")

#cambiamos elemento en el índice 2 (tercer elemento) por x
lista[2]="x"
print("lista despues de cambiar el tercer elemento", lista)

print("----------------------------")

#desempaquetamos los elementop d la lista en variables individuales
v1,v2,v3,v4,v5=lista
print("v1:", v1)
print("v2:", v2)
print("v3", v3)
print("v4:", v4)
print("v5:", v5)


print("----------------------------")

#agregar elementos a una lista vacía
datos=["Juan",25,"Ing"]

#desempaquetamos los elementos de la lista variables individuales
nombre,edad,profesion=datos
print("nombre:", nombre)
print("edad:", edad)
print("profesion:", profesion)



print("----------------------------")

#operador de copncartenación para concatenar listas

l1=[1,2,3]
l2=[4,5,6]

#concatenamos lad 2 listad usanfp el operador +
conca1=l1+l2
l1.extend(l2)
conca2=l1

print("concatenación  uasando el operador +", conca1)
print("concatenación  usando el método extend", conca2)

"""Taller

Integrantes:
Integrantes:
* Johan Beleño
* Emanuel Renteria
* Adrian Yepes
"""

#1
"""
rea una lista llamada frutas con los elementos: "manzana", "banano", "pera", "uva", "naranja".

Muestra el primer y el último elemento.

Agrega la fruta "mango" al final.

Elimina "pera" de la lista.

Imprime la lista final.
"""

frutas=["manzana", "banano", "pera", "uva", "naranja"]
#mostrar el 1mer y ultimo elemento
print("primer elemento", frutas[0])
print("primer elemento", frutas[4])

mango=frutas.append("mango") #se agrega mango
pera=frutas.remove("pera") #se elimina pera

print("lista con datosactulizados:", frutas)

#2

#Crea una lista llamada numeros con los números del 1 al 10. Muestra la suma total de los elementos. Muestra el número más grande y el más pequeño. Calcula el promedio de la lista.

# 1. creamos una lista llamada numeros con los numeros del 1 al 10.

numeros=[1,2,3,4,5,6,7,8,9,10]

print(f"lista de numeros: (numeros)")

# 2. mostramos la suma total de los elementos.
# usamos la funcion integrada sum()

suma_total = sum(numeros)
print(f"la suma total de los elementos es: {suma_total}")

#3.

#Creamos una lista con los nombres
nombres = ["Ana", "Luis", "Sofía", "Pedro", "Carla"]

#Usamos un ciclo for para imprimir todos los nombres
print("Nombres:")
for nombre in nombres:
  print(nombre)

#Usamos otro ciclo for para imprimir solo los nombres con más de 4 letras
print("Más de 4 letras:")
for nombre in nombres:
  if len(nombre)>4:
    print(nombre)

"""
Ejercicio 4:
Dada la lista edades = [12, 17, 18, 20, 15, 22, 13]:

Crea una nueva lista llamada mayores que contenga solo las edades mayores o iguales a 18.

Imprime la cantidad de personas mayores de edad y muestra la lista resultante.
"""

edades = [12, 17, 18, 20, 15, 22, 13]
mayor_edad=[]
for n in edades:
  if n >= 18:
    mayor_edad.append(n)
print(mayor_edad)

"""
Ejercicio 5:
Crea una lista con 5 notas de estudiantes.

Calcula el promedio.

Indica si el promedio es aprobado (≥3.0) o reprobado (<3.0).

Muestra las notas ordenadas de menor a mayor.
"""

# usaremos numeros flotantes (con decimales) para mayor precision.

notas = [3.5, 4.0, 2.8, 3.2, 5.0]

print(f"lista de notas ingresadas: {notas}")


suma_notas = sum(notas)

cantidad_notas = len(notas)

promedio = suma_notas / cantidad_notas

promedio_redondeado = round(promedio, 2)

print(f"el promedio de las notas es: {promedio_redondeado}")

nota_aprobacion = 3.0

if promedio_redondeado >= nota_aprobacion:
  print("el promedio es aprobado")
else:
  print("el promedio es reprobado")

# Mostrar notas ordenadas (menor a mayor)
notas.sort()

print(f"notas ordenadas de menor a mayor: {notas}")

#6.

#Creamos dos listas vacias
productos = []
precios = []

#Ciclo for para ingresar datos
for i in range(5):
  nombre = input(f"Ingrese el nombre del producto: ")
  precio = float(input(f"Ingrese el precio del producto: "))

#Añadimos cada elemento a las listas
  productos.append(nombre)
  precios.append(precio)

#Sumamos los precios
total = sum(precios)

#Determinamos cual es el producto mas caro y el mas barato
indice_max = precios.index(max(precios))
indice_min = precios.index(min(precios))

mas_caro = productos[indice_max]
mas_barato = productos[indice_min]

#Mostramos los resultados
print(f"Total: {total}")
print(f"Producto más caro {mas_caro} {max(precios)}")
print(f"Producto más barato {mas_barato} {min(precios)}")